---
title: "ESA Climate Sensitivity"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: custom.css
    social: menu
    df_print: paged
    navbar:
    - {title: "CCI", align: right, href: "https://defenders-cci.org"}
    - {title: "", icon: "fa-question-circle fa-lg", align: right, href: "mailto:adelach@defenders.org?subject=ESA climate sensitivity"}
    - {title: "", icon: "fa-github fa-lg", align: right, href: "https://github.com/Defenders-CCI/"}
runtime: shiny
---

```{r setup, include=FALSE}
library(DT)
library(flexdashboard)
library(plotly)
library(shiny)
library(shinydashboard)
library(tidyverse)
library(viridis)

dat <- readRDS("data/sensitivity_data_prepped_v2.rds")
dis <- readRDS("data/discussion_data_prepped_v2.rds")

taxa <- c("All", unique(dat$Taxon) %>% sort())
subtaxa <- c("All", unique(dat$Subtaxon) %>% sort())
region <- c("All", unique(dat$Lead_Region) %>% sort())
state <- c("All", 
           dis$State %>% 
             str_split(", | |,") %>% 
             unlist() %>% 
             str_trim() %>% 
             unique() %>%
             sort())
species <- unique(dat$species) %>% sort()
```

Overview
=====================================================

Filters {.sidebar}
-----------------------------------------------------
### Biodiversity

```{r}
selectInput(
  "taxa_1",
  "Vertebrate?",
  taxa
)

selectInput(
  "taxa_2",
  "Species group",
  subtaxa
)
```

### Area

```{r}
selectInput(
  "region_1",
  "Region",
  region
)

selectInput(
  "region_2",
  "State/territory",
  state
)
```

```{r}
helpText("Use the drop-downs to filter the data to your species group
         or area of interest. The chart will automatically update. A
         warning will show if the combination of filters gives no results.")
```

Row 1
-----------------------------------------------------
```{r}
usr_sel <- function(df, tx1, tx2, re1, re2) {
  if(tx1 != "All") {
    df <- filter(df, Taxon == tx1)
  }
  if(tx2 != "All") {
    df <- filter(df, Subtaxon == tx2)
  }
  if(re1 != "All") {
    df <- filter(df, Lead_Region == re1)
  }
  if(re2 != "All") {
    df <- filter(df, grepl(pattern = re2, State))
  }
  if(dim(df)[1] == 0) stop("No data match filters; please update selections.")
  return(df)
}

dat_select <- reactive({
  cur_dat <- usr_sel(dat, input$taxa_1, input$taxa_2,
                     input$region_1, input$region_2)
})

dis_select <- reactive({
  cur_dat <- usr_sel(dis, input$taxa_1, input$taxa_2,
                     input$region_1, input$region_2)
})

```

### Number of Sensitivity Factors

```{r}
renderPlotly({
  o1 <- dat %>% distinct(Scientific_Name, .keep_all = TRUE)
  d1 <- dat_select() %>% distinct(Scientific_Name, .keep_all = TRUE)
  p <- ggplot(data = d1, aes(n_sens_factors)) +
    geom_bar(data = o1, aes(n_sens_factors), alpha = 0.3) + 
    geom_bar(alpha = 0.7, fill = viridis(1)) + 
    labs(x = "# Sensitivity Factors",
         y = "# Species") +
    scale_fill_viridis(discrete = TRUE) +
    theme_bw() +
    theme(legend.position = "none")
  ggplotly(p) %>%
    layout(legend = list(orientation = "h"))
})
```

### Climate Change Discussed?

```{r}
renderPlotly({
  o1 <- dis
  d1 <- dis_select()
  pos <- table(o1$CC_Discuss) %>% sort(decreasing = TRUE) %>% names()
  p <- ggplot(data = d1, aes(CC_Discuss)) +
    geom_bar(data = o1, aes(CC_Discuss), alpha = 0.3) + 
    geom_bar(alpha = 0.7, fill = viridis(1)) + 
    labs(x = "",
         y = "# Species") +
    scale_fill_viridis(discrete = TRUE) +
    theme_bw() +
    theme(legend.position = "none")
  ggplotly(p) %>%
    layout(legend = list(orientation = "h"))
})
```

Row 2
-----------------------------------------------------

### Sensitivity Factors

```{r}
renderPlotly({
  o1 <- dat %>% 
    filter(Sens_Disc == "y")
  pos <- table(o1$Factor) %>% sort(decreasing = TRUE) %>% names()
  observe(print(pos))
  d1 <- dat_select() %>%
    filter(Sens_Disc == "y")
  p <- ggplot(data = d1, aes(Factor)) +
    geom_bar(data = o1, aes(Factor), alpha = 0.3) + 
    geom_bar(alpha = 0.7, fill = viridis(1)) + 
    labs(x = "",
         y = "# Species") +
    scale_fill_viridis(discrete = TRUE) +
    theme_bw() +
    theme(legend.position = "none") +
    scale_x_discrete(limits = pos) +
    theme(axis.text.x = element_text(angle = 25, hjust = 1))
  ggplotly(p) %>%
    layout(legend = list(orientation = "h"))
})
```

### Level of Discussion

```{r}
renderPlotly({
  o1 <- dis
  d1 <- dis_select()
  pos <- table(o1$Discuss_Level) %>% sort(decreasing = TRUE) %>% names()
  p <- ggplot(data = d1, aes(Discuss_Level)) +
    geom_bar(data = o1, aes(Discuss_Level), alpha = 0.3) + 
    geom_bar(alpha = 0.7, fill = viridis(1)) + 
    labs(x = "",
         y = "# Species") +
    scale_fill_viridis(discrete = TRUE) +
    theme_bw() +
    scale_x_discrete(limits = pos) +
    theme(axis.text.x = element_text(angle = 25, hjust = 1)) +
    theme(legend.position = "none")
  ggplotly(p) %>%
    layout(legend = list(orientation = "h"))
})
```



Species
=====================================================

Filters {.sidebar}
-----------------------------------------------------
```{r}
species <- unique(dat$species) %>% sort()

selectInput(
  "species_1",
  "Species",
  species
)
```

Main
-----------------------------------------------------
```{r}
cur_sp <- reactive({
  filter(dat, species == input$species_1)
})
```

Column 1 {data-width=250}
-----------------------------------------------------

```{r}
renderInfoBox({
  infoBox(
    cur_sp()$Factor[1],
    value = if_else(cur_sp()$Sens_Disc[1] == "y", "Yes", "No")
  )
})

renderInfoBox({
  infoBox(
    cur_sp()$Factor[2],
    value = if_else(cur_sp()$Sens_Disc[2] == "y", "Yes", "No")
  )
})

renderInfoBox({
  infoBox(
    cur_sp()$Factor[3],
    value = if_else(cur_sp()$Sens_Disc[3] == "y", "Yes", "No")
  )
})

renderInfoBox({
  infoBox(
    cur_sp()$Factor[4],
    value = if_else(cur_sp()$Sens_Disc[4] == "y", "Yes", "No")
  )
})
```

Row 2 {data-height=250}
----------------------------------------------------

```{r}
renderInfoBox({
  infoBox(
    cur_sp()$Factor[5],
    value = if_else(cur_sp()$Sens_Disc[5] == "y", "Yes", "No")
  )
})

renderInfoBox({
  infoBox(
    cur_sp()$Factor[6],
    value = if_else(cur_sp()$Sens_Disc[6] == "y", "Yes", "No")
  )
})

renderInfoBox({
  infoBox(
    cur_sp()$Factor[7],
    value = if_else(cur_sp()$Sens_Disc[7] == "y", "Yes", "No")
  )
})


renderInfoBox({
  infoBox(
    cur_sp()$Factor[8],
    value = if_else(cur_sp()$Sens_Disc[8] == "y", "Yes", "No")
  )
})

# DT::renderDataTable({
#   tab1 <- select(cur_sp(), Q_n, Question, Explanation, Sens_Disc)
#   DT::datatable(tab1)
# })
```

Row 3 {data-height=500}
----------------------------------------------------
